# Generated by Django 3.0.8 on 2020-07-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200721_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cookie_id',
            new_name='customer_cookie_id',
        ),
    ]
