# Generated by Django 3.0.8 on 2020-07-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200721_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_cookie_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
