# Generated by Django 3.0.8 on 2020-07-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200722_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depto',
            old_name='number_of_guests',
            new_name='capacity',
        ),
    ]
