# Generated by Django 3.0.8 on 2020-07-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200727_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
