# Generated by Django 3.0.8 on 2020-07-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
