# Generated by Django 3.0.8 on 2020-07-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
