# Generated by Django 3.0.8 on 2020-07-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200727_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='accepted',
            new_name='approved',
        ),
    ]
