# Generated by Django 3.0.8 on 2020-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200727_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptoreservation',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deptoreservation',
            name='deletion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
