# Generated by Django 3.0.8 on 2020-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200730_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptoreservation',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
